# Macro file for "rangeSim.cc"
# 
# compute the csda range of primary particle
#
/control/verbose 0
/run/verbose 0
#
#
/run/initialize
#
#
/rangesim/gun/setDefault
/gun/particle e-
#
/rangesim/det/setMat G4_Al
/rangesim/det/update
#
#
# Running differnet energies through alumnium
#
/gun/energy 10 MeV
/run/beamOn 100
/gun/energy 1 MeV
/run/beamOn 100
/gun/energy 100 keV
/run/beamOn 100
/gun/energy 10 keV
/run/beamOn 100
#
# Running through PS
#
/rangesim/det/setMat G4_POLYSTYRENE
/rangesim/det/update
/gun/energy 10 MeV
/run/beamOn 100
/gun/energy 1 MeV
/run/beamOn 100
/gun/energy 100 keV
/run/beamOn 100
/gun/energy 10 keV
/run/beamOn 100
#
# Running through Plastic Scintillator
#
/rangesim/det/setMat G4_PLASTIC_SC_VINYLTOLUENE
/rangesim/det/update
/gun/energy 10 MeV
/run/beamOn 100
/gun/energy 1 MeV
/run/beamOn 100
/gun/energy 100 keV
/run/beamOn 100
/gun/energy 10 keV
/run/beamOn 100
