# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Shooting a photon at the detector
# neutrons, electrons can be shot with: neutron, e-
/gun/particle gamma
/gun/energy 1.13 MeV
#/gun/particle neutron
#/gun/energy 1 eV
/gun/direction 0 0 1
/gun/position 0 0 -0.1 cm
/run/beamOn 1000
#
# Activate/inactivate physics processes
#
# /process/list
# /process/inactivate eBrem
#
