# Macro file for "rangeSim.cc"
# 
# compute the csda range of primary particle
#
/control/verbose 0
/run/verbose 0
#
#
/run/initialize
/rangesim/phys/setCuts 1 nm
/rangesim/det/setSize 1 m
#
#
/rangesim/gun/setDefault
/gun/particle e-
#
# Running differnet energies through alumnium
#
/rangesim/det/setMat G4_Al
/rangesim/det/update
/gun/energy 10 MeV
/run/beamOn 100000
/gun/energy 5 MeV
/run/beamOn 100000
/gun/energy 1 MeV
/run/beamOn 100000
/gun/energy 500 keV
/run/beamOn 100000
/gun/energy 100 keV
/run/beamOn 100000
/gun/energy 50 keV
/run/beamOn 100000
/gun/energy 10 keV
/run/beamOn 100000
#
# Running through PS
#
/rangesim/det/setMat G4_POLYSTYRENE
/rangesim/det/update
/gun/energy 10 MeV
/run/beamOn 100000
/gun/energy 5 MeV
/run/beamOn 100000
/gun/energy 1 MeV
/run/beamOn 100000
/gun/energy 500 keV
/run/beamOn 100000
/gun/energy 100 keV
/run/beamOn 100000
/gun/energy 50 keV
/run/beamOn 100000
/gun/energy 10 keV
/run/beamOn 100000
#
# Running through Plastic Scintillator
#
/rangesim/det/setMat G4_PLASTIC_SC_VINYLTOLUENE
/rangesim/det/update
/gun/energy 10 MeV
/run/beamOn 100000
/gun/energy 5 MeV
/run/beamOn 100000
/gun/energy 1 MeV
/run/beamOn 100000
/gun/energy 500 keV
/run/beamOn 100000
/gun/energy 100 keV
/run/beamOn 100000
/gun/energy 50 keV
/run/beamOn 100000
/gun/energy 10 keV
/run/beamOn 100000
#
# Running through Water 
#
/rangesim/det/setMat G4_WATER
/rangesim/det/update
/gun/energy 10 MeV
/run/beamOn 100000
/gun/energy 5 MeV
/run/beamOn 100000
/gun/energy 1 MeV
/run/beamOn 100000
/gun/energy 500 keV
/run/beamOn 100000
/gun/energy 100 keV
/run/beamOn 100000
/gun/energy 50 keV
/run/beamOn 100000
/gun/energy 10 keV
/run/beamOn 100000
