# Setting up verbosity
/tracking/verbose 0
/run/verbose 0
#
# Setting up the analysis
#
/Analysis/setParticleName testNeutron
/Analysis/setHistogramMax 5.0 MeV
#/Analysis/setHistogramMax 1.2 MeV
#
# Setting up the detector
#
/PolymerTransport/det/setAbsMat PS_Detector
/PolymerTransport/det/setGapMat G4_PLEXIGLASS
/PolymerTransport/det/setGapThick 2.5 cm
/PolymerTransport/det/setRadius 5 cm
/PolymerTransport/det/setAbsThick 5 cm
/PolymerTransport/det/update

# 
# Running the co60 beam source
#
#/control/execute macros/co60Source.mac
/control/execute macros/neutronSource.mac
/run/beamOn 1000
#
