# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Shooting a photon at the detector
# neutrons, electrons can be shot with: neutron, e-
/tracking/verbose 0 

/gun/particle gamma
/gun/direction 0 0 1
/gun/energy 1.1732 MeV
/run/beamOn 1000000
/gun/energy 1.3326 MeV
/run/beamOn 1000000
#
# Activate/inactivate physics processes
#
# /process/list
# /process/inactivate eBrem
#
