# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Shooting a photon at the detector
# neutrons, electrons can be shot with: neutron, e-
/tracking/verbose 2

/gun/particle neutron
/gun/energy 0.025 eV
/gun/direction 0 0 1
/gun/position 0 0 -3 cm
/run/beamOn 100000

#
# Activate/inactivate physics processes
#
# /process/list
# /process/inactivate eBrem
#
