#
/tracking/verbose 2 
#
# Setting up the detector
#
/PolymerTransport/det/setAbsMat PS_Detector
/PolymerTransport/det/setGapMat G4_POLYSTYRENE
/PolymerTransport/det/setAbsThick 25 um
/PolymerTransport/det/setGapThick 0.3175 cm
/PolymerTransport/det/update
#
# Shooting a photon at the detector (energies Cs137)
/gun/particle gamma
/gun/direction 0 0 1
/gun/energy 663 keV
/run/beamOn 1000000
#
# Shooting a thermal neutron at the detecotr
#
/gun/particle neutron
/gun/energy 0.025 eV
/gun/direction 0 0 1
/run/beamOn 10000

#
# Shooting a 5.48 MeV alpha (primary am241)
#
/gun/particle alpha
/gun/energy 5.48 MeV
/gun/direction 0 0 1
/run/beamOn 10000

