# Energy Depsostion Targets and Makefile
# Based on the Makefile defined by lmake

# PROBLEM SPECIFIC PARAMETES
neverclean := *.pdf *.ps
onlysources.tex := Calculations.tex IntrinsicEfficiency.tex LightYield.tex ComptonScatterSpectra.tex DNDO_DetectorPerformance.tex
BUILD_STRATEGY := pdflatex

# Setting up the viewers
UNAME := $(shell uname)
ifeq ($(UNAME),Linux)
	DVI_VIEWER = xdvi
	PS_VIEWER = evince
	PDF_VIEWER = evince
else
	DVI_VIEWER = open
	PS_VIEWER = open
	PDF_VIEWER = open
endif
